import "./globals.css";

// Theme
import { ThemeProvider } from "./theme-provider";

// ThemeChange Duration
import { switchThemeDuration } from "./constants";

// Header
import Navbar from '@/Sections/Navbar';

// Font
import poppins from "./font";

import ClientWrapper from './ClientWrapper'; // Adjust the path as necessary

export const metadata = {
  title: "RareLux",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} dark:bg-darkModeColor ${switchThemeDuration} `}>
        <ClientWrapper>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <Navbar />
            <div className="flex justify-center pt-[64px]">
              <div className="max-w-custom w-full">
                {children}
              </div>
            </div>
          </ThemeProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
