//css
import "./globals.css";

//Theme
import { ThemeProvider } from "./theme-provider";

//ThemeChange Duration
import { switchThemeDuration } from "./constants";

//Header
import Navbar from '@/components/Navbar';

//Font
import poppins from "./font";

export const metadata = {
  title: "RareLux",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
 return (
    <>
      <html lang="en">
        <body className={`${poppins.className}  dark:bg-[#0C1019] ${switchThemeDuration}`}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
