//css
import "./globals.css";

//Theme
import { ThemeProvider } from "./theme-provider";

//ThemeChange Duration
import { switchThemeDuration } from "./constants";

//Header
import Navbar from '@/Sections/Navbar';

//Font
import poppins from "./font";

//Meta Data for Title 
export const metadata = {
  title: "RareLux",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} dark:bg-[#0C1019] ${switchThemeDuration} `}>
        {/* theme provider can get the value for dark or light mode */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* Header */}
            <Navbar />
          {/* Main Content Container */}
          <div className="flex justify-center pt-[64px]">
            <div className="max-w-[2080px] w-full">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
